#!/bin/bash

#
# Build script for the Dreambox.
#

set -e;

vagrant destroy;

# Remove from VirtualBox.
# Useful for quickly re-running failed builds.
VM=$(vboxmanage list runningvms);
VM_ID=$(echo $VM | sed -E 's/dreambox\"\s{(.*)}.*/\1/');
vboxmanage controlvm $VM_ID poweroff && vboxmanage unregistervm $VM_ID --delete;

# Remove the output directories
rm -rf output-vmware-iso/;
rm -rf output-virtualbox-iso/;

if [[ ! -d '_builds' ]]; then
  # Create the _builds directory.
  mkdir '_builds';
else
  # Clear the _builds directory, rather than forcing the build.
  rm -f _builds/*;
fi;

# Remove the box from Vagrant to avoid collisions.
[[ $(vagrant box remove --force --all dreambox_pre/virtualbox 2> /dev/null) ]] || echo 'No Vagrant box to remove...';
[[ $(vagrant box remove --force --all dreambox_pre/vmware 2> /dev/null) ]] || echo 'No Vagrant box to remove...';

# Build.
packer build -var-file=templates/common.json templates/dreambox.json;

# Add the box to vagrant as 'dreambox_pre'.
vagrant box add --force dreambox_pre/virtualbox _builds/dreambox.virtualbox.*.box;
vagrant box add --force dreambox_pre/vmware _builds/dreambox.vmware.*.box;

exit $?;
