# -*- mode: ruby -*-
# vi: set ft=ruby :

require_relative 'config-setup.rb'
vm_config = Config::VM_CONFIG

Vagrant.configure(2) do |config|
  # Start bash as a non-login shell
  config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"

  vm_config['sites'].each do |site, conf|
    # Sets up the sync folder
    config.vm.synced_folder conf['local_root'], conf['root_path']
    # Runs user_setup
    config.vm.provision "shell",
      inline: "/bin/bash /usr/local/bin/user_setup",
      # Pass user_setup ENV variables to this script
      :env => conf
  end
end
