#!/bin/bash
#
# Create the SSL certificate, then finish setup
#
open_ssl_conf='/usr/lib/ssl/dreambox-openssl.cnf'
IFS=',' read -r -a HOST_LIST <<< "${hosts}"
HOST="${HOST_LIST[0]}"

# Check for a saved certificate and key
if [[ -r "/vagrant/certs/${name}.key" && -r "/vagrant/certs/${name}.crt" ]]; then
  # Use the saved certs
  echo "Using saved certs from /vagrant/certs/"
  cp -f /vagrant/certs/"${name}".* /usr/local/apache2/conf/
else
  # Build the hosts strings
  for (( i=1; i<=${#HOST_LIST[@]}; i++ )); do
    echo "DNS.${i} = ${HOST_LIST[$i-1]}" >> "${open_ssl_conf}"
  done

  # Create the certificate
  openssl req \
    -x509 -nodes \
    -days 365 \
    -newkey rsa:2048 \
    -extensions v3_req \
    -subj "/C=US/ST=Washington/L=Seattle/O=IT/CN=${HOST}/" \
    -keyout "/usr/local/apache2/conf/${name}.key" \
    -out "/usr/local/apache2/conf/${name}.crt" \
    -config "${open_ssl_conf}";

  # Create the certs directory
  [[ ! -d /vagrant/certs ]] && mkdir /vagrant/certs
  # Save these for next time
  cp -f /usr/local/apache2/conf/"${name}".* /vagrant/certs
fi

if [[ $? -lt 1 ]]; then
  echo -e "SSL certificate created: ${name}.crt\n"
else
  echo -e "SSL setup error..."
fi
