#!/bin/bash
#
# Create the web root and virtual host
#

trap "do_exit" TERM INT

# Ensure the script is run as SU
if [ "$(whoami)" != "root" ]; then
  echo
  echo "x ... failed! Rerun as root (sudo user_setup)";
  echo
  exit 1
fi

# Catch errors and provide feedback
function e_catch {
  PASS=false
  CLEAN=false

  for opt in $@; do
    case $opt in
            0)  PASS=true             ;;
            *)  MESSAGE=${@%%--clean} ;;
    esac
  done;

  if $PASS; then
    echo " ✓ ... ${MESSAGE:2}"
  else
    echo
    echo " x ... ${MESSAGE:2} failed!"
    do_exit
  fi
}

function do_exit {
  echo
  echo "${@}"
  echo "Exiting..."
  echo
  exit 1
}

##
# [host]       The first host listed for the site.
# [root_path]  The path to the site root.
# [vhost_file] The path to the vhost files for the site.
# [box_name]   The root config name; used as the certificate and key file names.
##
if [[ -n $host && -n $root_path && -n $vhost_file && -n $box_name ]]; then
  # Set the new vhost conf file in place
  cp /tmp/files/http/httpd-vhosts.conf "${vhost_file}"

  # Set Apache directory
  ESCAPED_SITE_ROOT=$(echo "$root_path" | sed 's/\(\W\)/\\\1/g');
  sed -i s/"\/usr\/local\/apache2\/htdocs"/"$ESCAPED_SITE_ROOT"/ "${vhost_file}";
  e_catch $? "httpd-vhosts.conf update"

  useradd -g users -s /bin/bash $username -u $DREAMBOX_UID
  cp -R /home/vagrant/.ssh /home/$username/.ssh
  echo -e "vagrant\nvagrant" | (passwd $username)
  cp /home/vagrant/.profile /home/$username/.profile
  echo "$username  ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
  chown -R $username /home/$username

  # ServerName
  sed -i s/"\(ServerName\ \)\w*\.\w*"/"\1${host}/" "${vhost_file}"

  # Update vhost file for SSL
  if [[ 'true' == $ssl ]]; then
    # Listen 443
    sed -i 's/\(#\ \)\(Listen\ \)\(80\)/\2443/' "${vhost_file}"
    # <VirtualHost *:443>
    sed -i 's/\*:80/\*:443/' "${vhost_file}"
    # SSLEngine on
    sed -i 's/\(SSLEngine\ \)\w*/\1on/' "${vhost_file}"
    # SSLCertificateFile
    sed -i s/'\(#\ \)\(SSLCertificateFile\ \)\(\/usr\/local\/apache2\/conf\/\)\w*\.crt'/"\2\3${box_name}\.crt"/ "${vhost_file}"
    # SSLCertificateKeyFile
    sed -i s/'\(#\ \)\(SSLCertificateKeyFile\ \)\(\/usr\/local\/apache2\/conf\/\)\w*\.key'/"\2\3${box_name}\.key"/ "${vhost_file}"

    e_catch $? "SSL setup"
    echo "For best results, add the certificate to your keychain"
  fi

  # Change ownership to Apache user
  chown -R www-data:www-data "${root_path}"
  e_catch $? "Permissions update"

  # Restart Apache
  /usr/local/apache2/bin/apachectl restart >/dev/null;
  e_catch $? "Apache restart"

  echo

  [[ $? -lt 1 ]] && echo -e "User setup complete.\n"
else
  do_exit 'Missing required Dreambox config settings.'
fi
